insert into heroes (id, name, publisher, image_url, category) values
-- Popular
('620','Spider-Man','Marvel Comics','spiderman','popular'),
('346','Iron Man','Marvel Comics','ironman','popular'),
('70','Batman','DC Comics','batman','popular'),
('644','Superman','DC Comics','superman','popular'),
('149','Captain America','Marvel Comics','captain-america','popular'),
('226','Doctor Strange','Marvel Comics','doctor-strange','popular'),
('720','Wonder Woman','DC Comics','wonder-woman','popular'),
('717','Wolverine','Marvel Comics','wolverine','popular'),
('659','Thor','Marvel Comics','thor','popular'),
('332','Hulk','Marvel Comics','hulk','popular'),
('213','Deadpool','Marvel Comics','deadpool','popular'),
('313','Hawkeye','Marvel Comics','hawkeye','popular'),
('414','Loki','Marvel Comics','loki','popular'),
('687','Venom','Marvel Comics','venom','popular'),
('630','Star Lord','Marvel Comics','star-lord','popular'),
('106','Black Panther','Marvel Comics','black-panther','popular'),
('30','Ant Man','Marvel Comics','ant-man','popular'),
-- Villains
('370','Joker','DC Comics','joker','villain'),
('222','Doctor Doom','Marvel Comics','doctor-doom','villain'),
('208','Darth Vader','Marvel Comics','darth-vader','villain'),
('479','Mysterio','Marvel Comics','mysterio','villain'),
('650','Terminator','Dark Horse Comics','terminator','villain'),
('225','Doctor Octopus','Marvel Comics','doctor-octopus','villain'),
('299','Green Goblin','Marvel Comics','green-goblin','villain'),
('423','Magneto','Marvel Comics','magneto','villain'),
-- X-Men
('196','Cyclops','Marvel Comics','cyclops','xmen'),
('480','Mystique','Marvel Comics','mystique','xmen'),
('638','Storm','Marvel Comics','storm','xmen'),
('75','Beast','Marvel Comics','beast','xmen'),
('567','Rogue','Marvel Comics','rogue','xmen'),
('185','Colossus','Marvel Comics','colossus','xmen'),
('490','Nightcrawler','Marvel Comics','nightcrawler','xmen'),
('710','Weapon X','Marvel Comics','weapon-x','xmen'),
('274','Gambit','Marvel Comics','gambit','xmen')
on conflict (id) do nothing;
