import { Image } from 'expo-image';
import type { HeadShape } from '../../lib/family/kinshipGender';

/**
 * Generated by `bun scripts/generate-avatars.ts --generic`, in the same flat
 * language as the character avatars so a placeholder sits in a row of real
 * faces without breaking the rhythm. Hand-drawn vector versions were tried
 * first and read as wigs on eggs — the model's are markedly better.
 */
const ART: Record<HeadShape, number> = {
  feminine: require('../../../assets/avatars/placeholder-feminine.png'),
  masculine: require('../../../assets/avatars/placeholder-masculine.png'),
  neutral: require('../../../assets/avatars/placeholder-neutral.png'),
};

/**
 * The stand-in for a family-tree entry that was never matched to a character.
 *
 * Around 80% of relatives are loose names with no hero row behind them, so they
 * can never have a real avatar. Rather than leaving those slots empty — which
 * made trees read as half-broken, a few pictures scattered through a list of
 * text — every row gets a head.
 *
 * These are deliberately FEATURELESS: no eyes, no mouth, nothing implying a
 * specific person. Only the outline varies, and which outline a row gets comes
 * from its stated role ("mother", "father"), never from guessing at a name —
 * see headShapeForRole.
 */
export function PlaceholderHead({ shape, size }: { shape: HeadShape; size: number }) {
  return (
    <Image
      source={ART[shape]}
      style={{ width: size, height: size }}
      contentFit="contain"
      transition={120}
    />
  );
}
