// Mystery-character silhouettes + vector FX kit for the reels/carousels.
//
// The artwork lives in assets/silhouettes/*.svg — generated by
// gen-silhouettes.mjs (Gemini image gen → potrace), original archetype designs
// (no franchise tracing, 100% our IP, safe in ads). This module loads a traced
// file, re-tints its ink, and adds a soft rim glow, so every call site keeps
// working with plain inline-SVG strings.
//
// Assignment is NOT hardcoded at call sites: `pickSilhouette(name, hint)`
// chooses deterministically from gender/alignment-aware pools so Superman
// never gets bat ears and Wonder Woman never gets anime spikes; the same
// character always maps to the same bust (series consistency).
import fs from 'node:fs';
import path from 'node:path';

const SVG_DIR = path.resolve(import.meta.dirname, '../../../assets/silhouettes');

// Busts (mystery characters) — the pickSilhouette pools draw from these.
const BUST_KINDS = ['hero', 'helm', 'brute', 'spikes', 'cowl', 'hood', 'slick', 'femlong', 'femcrop', 'caped'];
// Support kit (FX/emblems/backdrops) — also served by silhouette() for reuse.
const FX_KINDS = ['burst', 'bolt', 'clash', 'laurel', 'crownmark', 'linkmark', 'skyline', 'herolanding', 'flyby'];

const cache = new Map();
function loadAsset(kind) {
  if (cache.has(kind)) return cache.get(kind);
  const raw = fs.readFileSync(path.join(SVG_DIR, `${kind}.svg`), 'utf8');
  const vb = /viewBox="([\d. ]+)"/.exec(raw);
  const body = /(<g [\s\S]*<\/g>)/.exec(raw);
  if (!vb || !body) throw new Error(`silhouettes: unparseable trace for '${kind}'`);
  const [, , w, h] = vb[1].split(' ').map(Number);
  const asset = { viewBox: vb[1], w, h, body: body[1] };
  cache.set(kind, asset);
  return asset;
}

/** A traced kit asset as an inline SVG, re-tinted. `rim` drives a soft edge
 *  glow (drop-shadow — potrace's scaled transform makes stroke widths lie).
 *  `size` is the rendered WIDTH; height follows the traced aspect ratio. */
export function silhouette(kind = 'hero', { size = 220, rim = '#e0a83e', ink = '#0b1a24' } = {}) {
  const isBust = BUST_KINDS.includes(kind);
  const a = loadAsset(isBust || FX_KINDS.includes(kind) ? kind : 'hero');
  // Busts size by HEIGHT (consistent visual mass across narrow/wide archetypes
  // — the plates clip wide capes at their edges); FX assets size by width.
  const w = isBust ? Math.round((size * 0.86 * a.w) / a.h) : size;
  const h = isBust ? Math.round(size * 0.86) : Math.round((size * a.h) / a.w);
  const glow = rim ? ` style="filter:drop-shadow(0 0 ${Math.max(3, Math.round(size * 0.02))}px ${rim})"` : '';
  const body = a.body.replace('fill="#000000"', `fill="${ink}"`);
  return `<svg width="${w}" height="${h}" viewBox="${a.viewBox}" preserveAspectRatio="xMidYMid meet"${glow} xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
}

export const SILHOUETTE_KINDS = [...BUST_KINDS];
export const FX_ASSET_KINDS = [...FX_KINDS];

// ── Assignment ────────────────────────────────────────────────────────────────
// Pools by hint. Order matters only for hash spread; membership is the rule.
const POOL_M = ['hero', 'helm', 'spikes', 'brute', 'cowl', 'hood', 'caped'];
const POOL_F = ['femlong', 'femcrop', 'hood', 'cowl'];
const POOL_N = ['hero', 'helm', 'hood', 'cowl', 'femlong', 'femcrop', 'caped'];
const POOL_VILLAIN_M = ['slick', 'brute', 'hood', 'helm', 'cowl'];
const POOL_VILLAIN_F = ['slick', 'femlong', 'hood', 'femcrop'];

const hash = (s) => { let h = 0; for (const c of String(s)) h = (h * 31 + c.codePointAt(0)) >>> 0; return h; };

const poolFor = (hint = {}) => {
  const g = (hint.gender ?? '').toLowerCase();
  const bad = (hint.alignment ?? '').toLowerCase() === 'bad';
  return g === 'female' ? (bad ? POOL_VILLAIN_F : POOL_F)
    : g === 'male' ? (bad ? POOL_VILLAIN_M : POOL_M)
      : bad ? POOL_VILLAIN_M : POOL_N;
};

/**
 * Deterministic archetype pick for a character. `hint` carries the SAFE text
 * fields the data layer already exposes: { gender?, alignment? }. Same name ⇒
 * same bust, gender-matched when known, villains lean menacing.
 */
export function pickSilhouette(name, hint = {}) {
  const pool = poolFor(hint);
  return pool[hash(name) % pool.length];
}

/** Two distinct busts for a pair (VS plates, family reveals). */
export function pickSilhouettePair(aName, aHint, bName, bHint) {
  const a = pickSilhouette(aName, aHint);
  let b = pickSilhouette(bName, bHint);
  if (b === a) {
    const pool = poolFor(bHint);
    b = pool[(hash(bName) + 1) % pool.length];
    if (b === a) b = pool[(hash(bName) + 2) % pool.length];
  }
  return [a, b];
}
