#!/usr/bin/env node
// Prints the WCAG contrast of every palette token as TEXT on each of the app's
// canvases (paper / ink / band).
//
// WHY THIS EXISTS: the same brand colour is legible on one ground and invisible
// on the other — orange is 5.92:1 on ink and 2.58:1 on paper — and that single
// fact has caused the same bug more than once: an eyebrow styled for the dark
// stage, reused on the beige sheet, silently unreadable. The table in
// docs/architecture/design-system.md is generated by this script so it can be
// re-derived instead of trusted, and so it cannot drift when the palette moves.
//
//   node scripts/ui/contrast-matrix.mjs          human-readable
//   node scripts/ui/contrast-matrix.mjs --md     the markdown table for the doc
//
// This is a REPORT, not a gate. It cannot know which canvas a given call site
// actually renders on — that needs eyes. It tells you which pairings are
// impossible, so review can focus on the ones that are merely risky.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(resolve(here, '../../src/constants/colors.ts'), 'utf8');

// Parse the COLORS literal straight from source so the table can never drift
// from the palette it claims to describe.
const block = src.match(/export const COLORS = \{([\s\S]*?)\} as const;/);
if (!block) {
  console.error('Could not find the COLORS literal in src/constants/colors.ts');
  process.exit(1);
}
const PALETTE = Object.fromEntries(
  [...block[1].matchAll(/(\w+):\s*'(#[0-9a-fA-F]{3,6})'/g)].map((m) => [m[1], m[2]]),
);

const toRgb = (hex) => {
  let h = hex.replace('#', '');
  if (h.length === 3)
    h = h
      .split('')
      .map((c) => c + c)
      .join('');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
};
const channel = (c) => {
  const s = c / 255;
  return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
};
const luminance = ([r, g, b]) =>
  0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};

const CANVASES = {
  paper: toRgb(PALETTE.beige),
  ink: toRgb(PALETTE.deepNavy),
  band: toRgb(PALETTE.navy),
};

const AA = 4.5; // WCAG AA for body text

const rows = Object.entries(PALETTE)
  .map(([token, hex]) => {
    const fg = toRgb(hex);
    const on = Object.fromEntries(
      Object.entries(CANVASES).map(([name, bg]) => [name, contrast(fg, bg)]),
    );
    const safe = Object.keys(on).filter((n) => on[n] >= AA);
    return { token, hex, on, safe };
  })
  .sort((a, b) => a.on.paper - b.on.paper);

if (process.argv.includes('--md')) {
  console.log('| token | on paper | on ink | on band | safe as text on |');
  console.log('| --- | ---: | ---: | ---: | --- |');
  for (const r of rows) {
    const safe = r.safe.length ? r.safe.join(', ') : '**nothing — decoration only**';
    console.log(
      `| \`${r.token}\` | ${r.on.paper.toFixed(2)} | ${r.on.ink.toFixed(2)} | ${r.on.band.toFixed(2)} | ${safe} |`,
    );
  }
} else {
  console.log(`\nPalette contrast as TEXT (WCAG AA = ${AA}:1)\n`);
  console.log(`${'token'.padEnd(12)}${'paper'.padStart(8)}${'ink'.padStart(8)}${'band'.padStart(8)}   safe on`);
  for (const r of rows) {
    const safe = r.safe.length ? r.safe.join(', ') : 'nothing — decoration only';
    console.log(
      `${r.token.padEnd(12)}${r.on.paper.toFixed(2).padStart(8)}${r.on.ink.toFixed(2).padStart(8)}${r.on.band.toFixed(2).padStart(8)}   ${safe}`,
    );
  }
  const split = rows.filter((r) => r.safe.length && r.safe.length < 3);
  console.log(
    `\n${split.length} of ${rows.length} tokens are legible on some canvases and not others.`,
  );
  console.log('That asymmetry is the whole reason the text roles are split by canvas.\n');
}
