// Publish lane — outbound content in one place: the social posting queue
// (generated by the local Social Studio) and Explore's editorial campaigns.
// Merges the old top-level Social and Campaigns tabs; both panels self-fetch.
import { useState } from 'react';
import { SubTabs } from '../SubTabs';
import { SocialDomain } from './SocialDomain';
import { CampaignsDomain } from './CampaignsDomain';

export type PublishSub = 'social' | 'campaigns';

export function PublishLane() {
  const [sub, setSub] = useState<PublishSub>('social');
  return (
    <>
      <SubTabs<PublishSub>
        tabs={[
          { key: 'social', label: 'Social', icon: 'share-social-outline' },
          { key: 'campaigns', label: 'Campaigns', icon: 'megaphone-outline' },
        ]}
        active={sub}
        onChange={setSub}
      />
      {sub === 'social' ? <SocialDomain /> : <CampaignsDomain />}
    </>
  );
}
