-- Flat head-icon avatars generated by scripts/generate-avatars.ts.
-- Hosted on Cloudinary at hero-avatars/{id} (transparent PNG), the same
-- scheme portrait_url uses for hero-portraits/{id}.
alter table public.heroes
  add column if not exists avatar_url text;

comment on column public.heroes.avatar_url is
  'Cloudinary URL for the hero''s flat icon avatar (transparent PNG, square). Generated by scripts/generate-avatars.ts. Distinct from portrait_url, which is the large painterly side-profile portrait.';

-- Partial index: every read path wants "famous heroes that have an avatar",
-- and the column is null for the long tail we never generate for.
create index if not exists heroes_avatar_url_idx
  on public.heroes (fame_score desc)
  where avatar_url is not null;
