-- Relationship blurbs, batch 07. Same-cast band, pairs 401-500.
--
-- 48 written, 52 declined. The band has turned up an unusual concentration of
-- blood ties — Superman/Superboy, Black Panther/Shuri, Magneto/Quicksilver,
-- Juggernaut/Professor X (step-brothers), Wolverine/X-23, Thor/Odin, Odin/Loki —
-- most of which the graph had already labelled 'family' correctly for once.
--
-- Written under the tightened contract: specific without being precise. No issue
-- numbers or cover dates appear in this batch at all.

insert into public.hero_relationship_blurbs
  (hero_a, hero_b, blurb, author, verified, status, note, kind_correction)
values
-- ── Family ────────────────────────────────────────────────────────────────
('644', 'cv-1686', 'Kon-El was grown from Kryptonian and human DNA to replace Superman while he was dead, and had to be told afterwards that half of him is Lex Luthor. Superman gave him the family name anyway.', 'claude', false, 'written', null, null),
('106', 'h_170c1b60-7de7-4e69-a273-ad2b4c4d2381', 'Shuri is T''Challa''s younger sister, builds most of what Wakanda fights with, and has held the Black Panther mantle herself when he could not. She is the only person who talks to the king like a sibling.', 'claude', false, 'written', null, null),
('423', '536', 'Pietro Maximoff was written as Magneto''s son for decades, and the relationship works because Quicksilver inherited the arrogance without the cause. Marvel has since walked the parentage back and it keeps drifting home.', 'claude', false, 'written', null, null),
('374', '527', 'Cain Marko is Charles Xavier''s step-brother, and the Juggernaut is what a jealous boy became after finding a gem in a temple. The most powerful mutant mind on Earth cannot touch him, because the helmet was the point.', 'claude', false, 'written', null, null),
('717', 'cv-3560', 'Laura Kinney was made from Logan''s genetic material as a weapon, raised as one, and got out. He is her father in every sense the comics eventually admitted, and she is the one who took the name when he died.', 'claude', false, 'written', null, null),
('659', 'cv-3507', 'Odin threw Thor out of Asgard and trapped him in a mortal body to teach him humility, which is the origin of the character. Every version of Thor is a son trying to satisfy a father who does not explain himself.', 'claude', false, 'written', null, null),
('cv-3507', 'cv-4324', 'Odin took Loki as an infant from a battlefield and raised him beside his own son without telling him where he came from. Loki finding out is the wound the entire mythology runs on.', 'claude', false, 'written', null, null),
('30', '708', 'Hank Pym and Janet van Dyne founded the Avengers together and married, and the marriage is the source of the worst thing the character ever did. The comics have never let Pym past it, and Janet is the one who decided that.', 'claude', false, 'written', null, null),
('30', '697', 'Hank Pym built Ultron and Ultron built the Vision, which makes the kindest Avenger the grandson of the worst thing Pym ever made. Nobody in the family is comfortable with the lineage and all of them acknowledge it.', 'claude', false, 'written', null, null),
('cv-23879', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471', 'Wally West was Barry Allen''s nephew by marriage and got the same powers in the same freak accident, which is either the luckiest coincidence in comics or the point. He took the name after Barry died and would not give it back.', 'claude', false, 'written', null, null),
-- ── Marvel ────────────────────────────────────────────────────────────────
('222', 'cv-2151', 'Victor von Doom and Reed Richards were students together, and Doom''s face was ruined by an experiment Richards had warned him about. Doom has never accepted that the warning was correct rather than sabotage.', 'claude', false, 'written', null, null),
('333', 'cv-2151', 'Johnny Storm is Reed Richards'' brother-in-law and the member of the Fantastic Four least interested in being managed. The team is a family before it is a team, and Johnny is the one who makes that a problem.', 'claude', false, 'written', null, null),
('225', 'cv-1780', 'Otto Octavius courted May Parker and very nearly married her, in a storyline the comics have never entirely known what to do with. Spider-Man had to stop the wedding without being able to say why.', 'claude', false, 'written', null, null),
('299', 'cv-1780', 'Norman Osborn knows Spider-Man''s identity, which makes May Parker the most obvious lever in New York and the one he has reached for most. She is the reason the Goblin is treated as an emergency rather than a fight.', 'claude', false, 'written', null, null),
('185', '213', 'Colossus keeps trying to recruit Deadpool into the X-Men and Deadpool keeps treating it as a bit, and the running joke works because Piotr is entirely sincere. He is the one hero who has never given up on him.', 'claude', false, 'written', null, null),
('638', 'cv-3548', 'Storm mentored Kitty Pryde as the youngest X-Man and the two have been each other''s counterweight since — the goddess who leads and the girl who walks through walls and says the unsayable thing in the room.', 'claude', false, 'written', null, null),
('275', '630', 'Gamora and Peter Quill are the Guardians'' romance, and the joke Marvel keeps making is that the deadliest woman in the galaxy is being courted by a man with a mixtape. She has never once been written as impressed.', 'claude', false, 'written', null, null),
('655', 'h_a6e0f730-8cdf-4c40-9763-f48947ddac64', 'Thanos rebuilt Nebula with machinery every time she lost to Gamora, piece by piece, as punishment. She is the daughter he did not love, and the one still alive to say so.', 'claude', false, 'written', null, null),
('655', 'cv-3324', 'Mantis is an empath who can feel exactly what Thanos is, which makes her the one member of the Guardians who cannot pretend he is only a problem of force. She is also the one who can put him to sleep.', 'claude', false, 'written', null, null),
('550', 'cv-3202', 'Nick Fury fought the Red Skull in the war as an infantry sergeant, long before either of them was running anything. Fury is the one who treats him as a Nazi rather than as a supervillain, which the Skull finds insulting.', 'claude', false, 'written', null, null),
-- ── DC ────────────────────────────────────────────────────────────────────
('643', 'cv-4684', 'Brainiac bottled Kandor while Kara Zor-El was still on Krypton, which makes him a thief of her actual childhood rather than of a story she was told. Supergirl''s hatred of him is personal in a way Superman''s is not.', 'claude', false, 'written', null, null),
('cv-2350', 'cv-4916', 'Black Adam had the wizard''s power first and lost it for what he did with it, and Billy Batson is a child holding the same lightning. Adam''s objection is that a boy was given what he had to earn.', 'claude', false, 'written', null, null),
('69', 'cv-1690', 'Helena Bertinelli is a mob daughter who became a vigilante, and Batman has never fully trusted her because she has never fully promised not to kill. He keeps her close for exactly that reason.', 'claude', false, 'written', null, null),
('370', 'cv-1690', 'The Huntress grew up in a crime family the Joker helped destroy, which makes her one of the few people in Gotham with a grievance that predates the cape. She is also the one Batman watches most closely around him.', 'claude', false, 'written', null, null),
('69', '97', 'Dinah Lance is the Justice Leaguer Batman argues with as an equal rather than manages, and the one who has told him to his face when the plan is cruelty. She trained half the people he works with.', 'claude', false, 'written', null, null),
-- ── Star Wars ─────────────────────────────────────────────────────────────
('cv-2206', 'cv-5411', 'Qui-Gon Jinn was Obi-Wan Kenobi''s master and disagreed with him constantly, and died leaving him a promise to train a boy the Council had refused. Kenobi keeps that promise and it destroys everything.', 'claude', false, 'written', null, null),
('cv-2206', 'cv-5392', 'Count Dooku trained Qui-Gon Jinn, which makes him Obi-Wan Kenobi''s grand-master and the man who taught his teacher. Their duel is a Sith taking apart the lineage he came from and enjoying it.', 'claude', false, 'written', null, null),
('729', 'cv-5392', 'Dooku was Yoda''s student before he was a Sith Lord, and their duel is an old master finding out what his own teaching produced. Yoda wins the fight and loses the argument, which is the prequels in miniature.', 'claude', false, 'written', null, null),
('729', 'cv-5411', 'Qui-Gon Jinn learned from Yoda and then spent his career ignoring the Council, and is the one Jedi who found a way to persist after death. Yoda is the first person he teaches it to.', 'claude', false, 'written', null, null),
('cv-16164', 'cv-5395', 'Mace Windu had Palpatine disarmed and beaten, and chose to execute him rather than arrest him — which is the moment Anakin intervenes. Palpatine spends that scene performing helplessness and winning with it.', 'claude', false, 'written', null, null),
('127', 'cv-5395', 'Mace Windu beheaded Jango Fett in an arena while Boba watched, and the boy carried the helmet away. Everything Boba Fett becomes is a child''s response to that afternoon.', 'claude', false, 'written', null, null),
('cv-2206', 'cv-5395', 'Two of the last Council masters, and they disagreed about Anakin Skywalker from the start — Windu never trusted him and Kenobi vouched for him. Windu was right, and it is Kenobi who has to live with it.', 'claude', false, 'written', null, null),
-- ── Manga, games, animation ───────────────────────────────────────────────
('cv-40722', 'cv-40737', 'Frieza destroyed the Saiyan homeworld and kept Vegeta as a servant afterwards, which is the humiliation the whole character is built to escape. Vegeta finally kills him and it does not help as much as he expected.', 'claude', false, 'written', null, null),
('cv-6467', 'h_5aea1d74-5e71-4dbf-af0f-1588b0f44cb0', 'Bumblebee is the smallest Autobot and Optimus Prime keeps sending him ahead alone, which is either the greatest trust in the war or the worst posting. He usually cannot speak, and it never stops him reporting back.', 'claude', false, 'written', null, null),
('cv-4103', 'h_5aea1d74-5e71-4dbf-af0f-1588b0f44cb0', 'Megatron tore out Bumblebee''s voice box, which is the injury the character is best known for and the reason he communicates through the radio. It was done to make a point to Optimus Prime rather than to him.', 'claude', false, 'written', null, null),
('h_4536f6a7-f50e-42d5-a258-e97b36e0abe4', 'h_d30e84f8-bd53-4058-aaed-7ae7724f4380', 'Miss Piggy decided she and Kermit are a couple and has been operating on that basis ever since, and the joke only works because the frog has never quite said no. The karate chop arrives whenever he tries.', 'claude', false, 'written', null, null),
('h_87117684-4467-403b-a57c-2cad3d23ebb1', 'h_c3d391aa-63dc-46fd-bcdf-e2d193d72474', 'Misty followed Ash Ketchum across two regions ostensibly over a bicycle he destroyed, and the bicycle is a running joke the show refuses to resolve. She is the first person who ever travelled with him.', 'claude', false, 'written', null, null),
('h_87117684-4467-403b-a57c-2cad3d23ebb1', 'h_da69b67c-244e-4542-a63a-57161083c16c', 'Bulbasaur joined Ash Ketchum reluctantly and became the one who breaks up fights between the others, which is unusual for a starter — it is the only Pokémon on the team with a job rather than a role.', 'claude', false, 'written', null, null),
('cv-52213', 'h_1955e1bf-8d71-4e3e-a623-3bdabfbe0664', 'Mewtwo was made in a laboratory to be the strongest, and the first film has him fight a cloned Pikachu to prove originals are worthless. It ends with Pikachu refusing to fight back, which is what actually stops him.', 'claude', false, 'written', null, null),
('cv-52213', 'cv-52626', 'Charizard spent a long stretch of the show refusing to obey Ash Ketchum at all, and Pikachu is the one who kept working while it sulked. The two are the poles of the team: the one who always turns up and the one who might.', 'claude', false, 'written', null, null),
('cv-3402', 'cv-3403', 'Lisa Simpson is the only one who talks to Maggie as though she is listening, and the show has repeatedly implied she is right. They are the two Simpsons the writers protect.', 'claude', false, 'written', null, null),
('h_63c17e21-0a31-4b99-b4cc-8462c0ae8743', 'h_fe4d8b42-81a9-4438-89a0-a7b51ed195ec', 'In Hesiod, Cronos castrates his father and throws the remains into the sea, and Aphrodite is what rises from the foam. The goddess of love in the oldest telling is the direct product of the most violent act in the myth.', 'claude', false, 'written', null, null),
('234', '630', 'Drax takes everything Peter Quill says literally, which is the Guardians'' most reliable joke and also the reason the two of them work — Quill lies constantly and Drax is immune to it.', 'claude', false, 'written', null, null),
('234', 'h_39f78998-cf7e-411c-a5a9-810f483a3675', 'Drax and Groot are the two Guardians with the smallest vocabularies and the fewest misunderstandings, and the films quietly pair them off in fights. Neither has ever needed the other explained.', 'claude', false, 'written', null, null),
('275', 'h_39f78998-cf7e-411c-a5a9-810f483a3675', 'Groot is the only Guardian Gamora has never had to be suspicious of, which for someone raised by Thanos is not a small thing. She is also one of the few who does not need Rocket to translate.', 'claude', false, 'written', null, null),
('213', 'cv-3548', 'Deadpool has pursued Kitty Pryde with the full force of his personality and she is entirely unmoved, which the comics play as her win rather than his joke. She can also phase out of the room, and does.', 'claude', false, 'written', null, null),
('423', 'cv-3548', 'Magneto has tried to recruit Kitty Pryde since she was a teenager, and she is the X-Man who tells him to his face that surviving a camp does not license what he does with it. He has never had an answer for her.', 'claude', false, 'written', null, null),
('185', '638', 'Piotr Rasputin and Ororo Munroe joined the X-Men in the same relaunch and have anchored the team since — the strongest man on it and the one who leads it. Neither has ever wanted the other''s job.', 'claude', false, 'written', null, null),
-- ── Declines ──────────────────────────────────────────────────────────────
('423', '480', null, 'claude', false, 'nothing_to_say', 'Brotherhood roster; nothing durable between them', null),
('480', '638', null, 'claude', false, 'nothing_to_say', 'X-Men adjacency; nothing durable', null),
('cv-52213', 'h_da69b67c-244e-4542-a63a-57161083c16c', null, 'claude', false, 'nothing_to_say', 'team-mates on Ash''s roster; the tie that matters is to Ash', null),
('cv-52213', 'h_c3d391aa-63dc-46fd-bcdf-e2d193d72474', null, 'claude', false, 'nothing_to_say', 'travelling companions; Pikachu''s tie is to Ash', null),
('cv-52213', 'h_2cefe34a-fdc2-43d2-b759-ad1c10f6e2de', null, 'claude', false, 'nothing_to_say', 'team-mates on Ash''s roster', null),
('527', 'cv-3548', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('527', '536', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('550', '659', null, 'claude', false, 'nothing_to_say', 'Red Skull belongs to Captain America', null),
('579', 'cv-3202', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('579', '714', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('638', '75', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('687', 'cv-1780', null, 'claude', false, 'nothing_to_say', 'Venom threatens everyone Peter knows; nothing specific to May', null),
('687', 'cv-1487', null, 'claude', false, 'nothing_to_say', 'Eddie Brock worked for the Globe, not the Bugle; the tie is thin', null),
('703', 'cv-3202', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('703', '714', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('729', 'cv-5395', null, 'claude', false, 'nothing_to_say', 'Council colleagues; nothing specific between them', null),
('17', 'h_c641fc32-86de-4e33-a5e9-0a7daa34d10f', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('cv-6129', 'h_c641fc32-86de-4e33-a5e9-0a7daa34d10f', null, 'claude', false, 'nothing_to_say', 'rogues-gallery cross product', null),
('69', 'h_efed1d20-5b5c-412e-9f76-860af06b75dd', null, 'claude', false, 'nothing_to_say', 'League roster only', null),
('127', 'cv-6355', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('149', 'cv-2262', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('185', '423', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('cv-5392', 'cv-6335', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('274', '527', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('306', 'cv-4916', null, 'claude', false, 'nothing_to_say', 'League-wide antagonism', null),
('332', 'cv-2262', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('339', '423', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('339', '638', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('346', 'cv-2262', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('354', 'cv-6335', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('354', 'cv-2206', null, 'claude', false, 'nothing_to_say', 'same films, no relationship of consequence', null),
('354', 'cv-2594', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('423', '490', null, 'claude', false, 'nothing_to_say', 'the Nightcrawler parentage runs through Mystique, not Magneto', null),
('432', 'cv-4916', null, 'claude', false, 'nothing_to_say', 'League-wide antagonism', null),
('cv-4885', 'h_c641fc32-86de-4e33-a5e9-0a7daa34d10f', null, 'claude', false, 'nothing_to_say', 'rogues-gallery cross product', null),
('536', '638', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('536', '659', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('cv-2594', 'cv-5392', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('cv-2594', 'cv-5411', null, 'claude', false, 'nothing_to_say', 'same films, no relationship', null),
('550', '714', null, 'claude', false, 'nothing_to_say', 'the Winter Soldier''s handlers were Soviet, not the Skull', null),
('cv-3718', 'h_c641fc32-86de-4e33-a5e9-0a7daa34d10f', null, 'claude', false, 'nothing_to_say', 'rogues-gallery cross product', null),
('589', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('644', '97', null, 'claude', false, 'nothing_to_say', 'League roster only', null),
('cv-55028', 'cv-6335', null, 'claude', false, 'nothing_to_say', 'same saga, no relationship', null),
('cv-55028', 'cv-6334', null, 'claude', false, 'nothing_to_say', 'same saga, no relationship', null),
('30', 'cv-1451', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null),
('30', '680', null, 'claude', false, 'nothing_to_say', 'the Ultron tie that matters is Pym building him', null),
('35', '717', null, 'claude', false, 'nothing_to_say', 'X-Men roster only', null),
('63', 'h_15a572bc-4624-4fe9-9dff-1eff9a94781b', null, 'claude', false, 'nothing_to_say', 'Ace is Batman''s dog; nothing specific to Barbara', null),
('106', '379', null, 'claude', false, 'nothing_to_say', 'Kang is a team-wide threat', null),
('106', '589', null, 'claude', false, 'nothing_to_say', 'Avengers roster only', null)
on conflict (hero_a, hero_b) do nothing;
