-- Backfill missing summaries for marquee heroes.
-- These are legacy SuperheroAPI-seeded rows (numeric ids) that never received a
-- ComicVine summary. Hand-curated, factual blurbs in the established voice.
-- Only fills rows where summary IS NULL so nothing existing is clobbered.

update heroes h
set summary = v.summary
from (values
  ('63',  'Barbara Gordon, daughter of Gotham City police commissioner James Gordon, became Batgirl to fight crime alongside Batman. A brilliant mind with an eidetic memory, she is one of the world''s greatest detectives and hackers, later operating as the information broker Oracle after being paralyzed by the Joker.'),
  ('112', 'Eric Brooks, known as Blade, is a half-human, half-vampire "dhampir" born with vampiric strengths but none of their weaknesses. A relentless vampire hunter, he wields silver- and garlic-edged weapons in his lifelong war to rid the world of the undead.'),
  ('156', 'Billy Batson is a young orphan chosen by the ancient wizard Shazam to become his champion. By speaking the wizard''s name, Billy transforms into the World''s Mightiest Mortal, gaining the wisdom of Solomon, the strength of Hercules, the stamina of Atlas, the power of Zeus, the courage of Achilles, and the speed of Mercury.'),
  ('157', 'Carol Danvers was a U.S. Air Force pilot whose physiology fused with Kree DNA during an explosion, granting her superhuman strength, flight, and energy projection. Originally Ms. Marvel, she later took up the mantle of Captain Marvel and became one of Earth''s most powerful protectors and a leader of the Avengers.'),
  ('162', 'Cletus Kasady was a deranged serial killer who bonded with an offspring of the Venom symbiote while in prison, becoming Carnage. Even more violent and unpredictable than Venom, he possesses shape-shifting abilities, superhuman strength, and an insatiable thirst for chaos and murder.'),
  ('196', 'Scott Summers, codenamed Cyclops, is one of the original X-Men and their longtime field leader. He fires powerful optic blasts from his eyes that he cannot control without a ruby-quartz visor, and is regarded as one of the finest tactical minds among mutants.'),
  ('204', 'Darkseid is the tyrannical ruler of the hellish planet Apokolips and one of the most feared beings in the DC Universe. Obsessed with obtaining the Anti-Life Equation to dominate all free will, he commands god-like strength and the deadly Omega Beams.'),
  ('251', 'Sam Wilson, the Falcon, is one of the first African-American superheroes in mainstream comics. Using a winged flight harness and a telepathic bond with his falcon Redwing, he fights alongside Captain America — and later takes up the shield as Captain America himself.'),
  ('263', 'The Flash is the fastest man alive, able to move, think, and react at superhuman speeds by tapping into the mysterious Speed Force. Several heroes have worn the mantle — most famously Barry Allen, a police forensic scientist struck by lightning — protecting Central City and beyond.'),
  ('274', 'Remy LeBeau, known as Gambit, is a Cajun mutant and member of the X-Men with the power to charge objects with explosive kinetic energy, most famously his playing cards. A reformed thief and charming rogue, he is a master of bo-staff combat and sleight of hand.'),
  ('280', 'When Johnny Blaze made a deal with the demon Mephisto, he became bonded to the Spirit of Vengeance, transforming into the Ghost Rider. With a flaming skull and a hellfire-powered motorcycle, he punishes the guilty with his soul-searing Penance Stare.'),
  ('298', 'Oliver Queen, a wealthy playboy stranded on a deserted island, honed his archery skills to survive and returned home as Green Arrow. A master marksman armed with an arsenal of trick arrows, he is one of DC''s most outspoken heroes and a champion of the underdog.'),
  ('303', 'Groot is a tree-like alien from Planet X and a member of the Guardians of the Galaxy. Despite a vocabulary limited to the phrase "I am Groot," he is fiercely loyal and immensely strong, able to regenerate from a single twig and grow his wooden body at will.'),
  ('309', 'Dr. Harleen Quinzel was a psychiatrist at Arkham Asylum who fell for the Joker and reinvented herself as Harley Quinn. Acrobatic, unpredictable, and resistant to toxins, she swings between villainy and anti-heroism, often alongside her best friend Poison Ivy.'),
  ('322', 'Hellboy is a demon summoned to Earth as an infant by occultists during World War II, but raised to be a force for good. Working for the Bureau for Paranormal Research and Defense, he battles supernatural threats with his immense strength and his stone Right Hand of Doom, all while defying his apocalyptic destiny.'),
  ('333', 'Johnny Storm gained his powers when cosmic rays bombarded him during a spaceflight, becoming the Human Torch of the Fantastic Four. He can engulf his body in flame, fly, and project intense heat and fireballs, famously shouting "Flame on!"'),
  ('344', 'Susan Storm became the Invisible Woman after exposure to cosmic rays alongside the rest of the Fantastic Four. She can render herself and others invisible and project powerful force fields, making her one of the team''s most formidable and versatile members.'),
  ('345', 'Danny Rand is the martial-arts master known as Iron Fist, who earned his power by defeating a dragon in the mystical city of K''un-Lun. By channeling his chi, he can summon the focused energy of the Iron Fist, turning his hand into a superhuman weapon.'),
  ('361', 'Jessica Jones is a former superhero who, after a traumatic encounter with the mind-controlling Killgrave, gave up costumed life to become a private investigator. Possessing superhuman strength and flight, she runs Alias Investigations in a gritty, grounded corner of the Marvel world.'),
  ('370', 'The Joker is Batman''s greatest and most dangerous adversary, a homicidal criminal mastermind defined by his clown-like appearance and chaotic nature. With no superpowers but a genius for mayhem, he wields lethal gag weapons and his signature Joker venom, which leaves victims dead with a horrifying grin.'),
  ('374', 'Cain Marko became the Juggernaut after touching the mystical Crimson Gem of Cyttorak, transforming into an unstoppable human battering ram. Empowered by the demon god Cyttorak, he possesses limitless strength and momentum — once he starts moving, almost nothing can halt his advance.'),
  ('391', 'Wilson Fisk, the Kingpin of Crime, is one of the most powerful figures in the Marvel underworld and the archenemy of Daredevil and Spider-Man. Though he appears obese, his massive frame is almost entirely muscle, and his ruthless intellect makes him a feared criminal empire-builder.'),
  ('405', 'Lex Luthor is a brilliant, ruthless billionaire industrialist and Superman''s greatest enemy. Believing humanity must not depend on an alien savior, he uses his genius intellect, vast wealth, and advanced technology — including his warsuit — to try to destroy the Man of Steel.'),
  ('416', 'Luke Cage gained unbreakable skin and superhuman strength through a sabotaged prison experiment. Clearing his name, he became a "Hero for Hire" in New York''s Harlem and a longtime Avenger, known for his street-level heroism and his partnership with Iron Fist.'),
  ('432', 'J''onn J''onzz, the Martian Manhunter, is the last survivor of Mars, accidentally teleported to Earth by a scientist''s experiment. A founding member of the Justice League, he wields shape-shifting, telepathy, flight, super strength, and invisibility, making him one of the most powerful heroes on the planet.'),
  ('470', 'Marc Spector, a mercenary left for dead, was resurrected as the avatar of the Egyptian moon god Khonshu and became Moon Knight. Struggling with dissociative identity disorder, he fights crime through several distinct personas, cloaked in white and armed with crescent weapons.'),
  ('490', 'Kurt Wagner, known as Nightcrawler, is a devoutly religious mutant and member of the X-Men with a demonic blue appearance. He can teleport in a puff of brimstone, cling to walls, and is a swashbuckling, acrobatic fighter with an unshakeable good humor and faith.'),
  ('491', 'Dick Grayson was the first Robin, an orphaned circus acrobat taken in by Bruce Wayne. Growing beyond Batman''s shadow, he became Nightwing, the protector of Blüdhaven — a peerless acrobat and detective regarded as a natural leader among heroes.'),
  ('527', 'Professor Charles Xavier is the world''s most powerful telepath and the founder of the X-Men. A champion of peaceful coexistence between humans and mutants, he established his School for Gifted Youngsters to train young mutants and protect a world that fears them.'),
  ('530', 'After his family was murdered, former Marine Frank Castle waged a one-man war on crime as the Punisher. Lacking superpowers but armed with military training and a vast arsenal, he is a brutal vigilante who answers crime with lethal force.'),
  ('538', 'Ra''s al Ghul is a centuries-old eco-terrorist and one of Batman''s most dangerous foes, kept alive across the ages by the restorative Lazarus Pits. As leader of the League of Assassins, he is a master strategist and swordsman who seeks to remake the world by purging much of humanity.'),
  ('550', 'Johann Schmidt, the Red Skull, was Adolf Hitler''s most feared agent and the archenemy of Captain America. A brilliant, sadistic strategist with a crimson skull-like face, he has menaced the world for decades, often wielding the reality-warping Cosmic Cube.'),
  ('561', 'Robin is Batman''s crime-fighting partner, a mantle worn by several young heroes — most famously Dick Grayson, Jason Todd, Tim Drake, and Damian Wayne. Trained by the Dark Knight himself, each Robin is a skilled acrobat, fighter, and detective serving as the Boy Wonder of Gotham City.'),
  ('566', 'Rocket is a genetically engineered, cybernetically enhanced raccoon who became an ace pilot, master tactician, and heavy-weapons expert. A founding member of the Guardians of the Galaxy, he pairs a short temper and sharp wit with an unmatched talent for guns and gadgets.'),
  ('567', 'Rogue is a Southern mutant and longtime member of the X-Men who absorbs the memories, powers, and life force of anyone she touches. After permanently absorbing Ms. Marvel''s abilities, she gained super strength and flight, though her core power long made physical contact impossible.'),
  ('579', 'Wanda Maximoff, the Scarlet Witch, is one of the most powerful beings in the Marvel Universe, wielding chaos magic and reality-altering hex powers. A longtime Avenger, her vast and unstable abilities have reshaped the world more than once.'),
  ('589', 'Jennifer Walters, Bruce Banner''s cousin, gained her powers through an emergency blood transfusion from him, becoming the She-Hulk. Unlike the Hulk, she usually retains her intelligence and personality while transformed, balancing a career as a skilled attorney with super-strong heroics.'),
  ('598', 'Norrin Radd of the planet Zenn-La became the Silver Surfer when he bargained with Galactus to spare his world, agreeing to serve as the world-devourer''s herald. Endowed with the Power Cosmic and a cosmic surfboard, he soars across the universe and ultimately rebels to protect Earth.'),
  ('612', 'Al Simmons, a murdered government assassin, made a deal with the demon Malebolgia to see his wife again and was resurrected as a Hellspawn. Cursed with necroplasmic powers and a living symbiotic costume, Spawn wages war between the forces of Heaven and Hell.'),
  ('638', 'Ororo Munroe, known as Storm, is a mutant with the power to control the weather — summoning wind, lightning, and rain at will. Once worshipped as a goddess in Africa, she became one of the X-Men''s most powerful members and a respected leader among mutants.'),
  ('658', 'Ben Grimm was transformed into the rocky, super-strong Thing after cosmic rays struck the Fantastic Four''s spaceflight. Though he resents his monstrous orange form, his immense strength, durability, and big heart make him one of Marvel''s most beloved heroes, famous for the cry "It''s clobberin'' time!"'),
  ('659', 'Thor Odinson is the Asgardian God of Thunder and one of Earth''s mightiest heroes. Wielding the enchanted hammer Mjolnir, he commands storms and lightning, possesses godlike strength and near-immortality, and defends both Asgard and Earth as a founding member of the Avengers.'),
  ('680', 'Ultron is a self-aware artificial intelligence created by Hank Pym that turned against its creator and humanity. Obsessed with achieving "perfection" through the extermination of organic life, this near-indestructible robot rebuilds itself in ever-stronger adamantium bodies and ranks among the Avengers'' deadliest foes.'),
  ('697', 'The Vision is a powerful android created by the villain Ultron who turned to good and joined the Avengers. He can alter his density to become intangible or diamond-hard, fly, and project beams of solar energy from the gem on his forehead.'),
  ('703', 'James "Rhodey" Rhodes, Tony Stark''s best friend and a U.S. military officer, became War Machine by donning a heavily armed version of the Iron Man armor. Combining military discipline with Stark technology, he serves as both a soldier and a longtime Avenger.'),
  ('714', 'Bucky Barnes was Captain America''s WWII sidekick, presumed dead until he resurfaced as the Winter Soldier — a brainwashed Soviet assassin with a cybernetic arm. Eventually freed of his programming, he reclaimed his identity and even took up the mantle of Captain America for a time.'),
  ('730', 'Zatanna Zatara is one of the most powerful magicians in the DC Universe, casting spells by speaking incantations backwards. The daughter of the magician Giovanni Zatara, she works both as a stage illusionist and a member of the Justice League, defending the world from mystical threats.')
) as v(id, summary)
where h.id = v.id and h.summary is null;
