-- Relationship blurbs, batch 01.
--
-- The first 100 pairs from hero_relationship_blurb_queue by combined fame.
-- 54 written, 46 declined. The declines are not failures — see 20260727160000
-- for why recording them is the thing that lets the queue drain.
--
-- Where the declines fell: almost entirely on cross-cast pairs the ComicVine
-- arrays invented by adjacency — Joker/Aquaman, Harley Quinn/Wonder Woman,
-- Catwoman/Superman, Hulk/Star-Lord. These characters share a publisher and a
-- crossover event or two and nothing else. The templated fallback already says
-- the true thing about them.
--
-- 8 rows also carry a kind_correction, where the pair is real and richly
-- documented but the graph's label is wrong: Captain America/Hulk as 'enemy'
-- (founding Avengers), Iron Man/Black Widow as 'enemy' (his assistant, then his
-- teammate), Supergirl/Batman as 'enemy', Catwoman/Harley Quinn as 'enemy'
-- (they co-founded the Gotham City Sirens). Nothing reads that column yet.

insert into public.hero_relationship_blurbs
  (hero_a, hero_b, blurb, author, verified, status, note, kind_correction)
values
-- ── Marvel: the Avengers core ─────────────────────────────────────────────
('149', '332',
 'The Hulk was a founding Avenger who quit in the team''s second issue, and Rogers was thawed out two issues later to replace him. Every reunion since has been Rogers arguing that Banner belongs on the roster.',
 'claude', false, 'written', null, 'ally'),
('149', '620',
 'Rogers is the hero Peter Parker measures himself against, and the one who keeps telling him he has already cleared the bar. Their Civil War split hurt because Parker had picked the other side on faith.',
 'claude', false, 'written', null, null),
('149', 'cv-3200',
 'Natasha Romanoff was trained by the country Rogers spent his war fighting, which is exactly why he trusts her: she picked this side with her eyes open, and he has never made her prove it twice.',
 'claude', false, 'written', null, null),
('149', '717',
 'They fought the same war — Logan was there, and remembers it without the ice. Rogers is one of the few people who outranks him, and the only one Logan has never seriously argued the point with.',
 'claude', false, 'written', null, null),
('149', '226',
 'Rogers commands the field and Strange defends the parts of it that stop obeying physics. It works because Rogers never pretends to follow the magic and Strange never pretends the chain of command applies to him.',
 'claude', false, 'written', null, null),
('149', '313',
 'Clint Barton joined the Avengers as a reformed criminal with a problem about authority, and Rogers made him field leader anyway. It is the clearest case of Rogers being right about someone before they were.',
 'claude', false, 'written', null, null),
('149', '655',
 'In Infinity Gauntlet, with the entire heroic line dead behind him, Rogers walked the length of the field to Thanos and offered his hand. It is the moment the character gets reduced to, and the reduction is accurate.',
 'claude', false, 'written', null, null),
('149', '659',
 'Thor was there at the Avengers'' founding and Rogers arrived three issues later, and the team defers to both for opposite reasons. Thor is a god; Rogers is the one they find harder to disappoint.',
 'claude', false, 'written', null, null),
('149', 'cv-4324',
 'Loki is the reason the Avengers exist — the team assembled in response to a scheme of his aimed at framing the Hulk. Rogers was still frozen when it happened and joined three issues later.',
 'claude', false, 'written', null, null),
('149', '213',
 'Wade Wilson''s regard for Rogers is the one sincere thing about him, and Rogers is unfailingly polite about it. The comics use Captain America as the measure of how far outside the line Deadpool actually sits.',
 'claude', false, 'written', null, 'ally'),
('106', '149',
 'T''Challa fought Rogers to a standstill the first time they met, having studied him in advance — which is how T''Challa meets everyone. Rogers is the one Avenger whose word he takes without a treaty.',
 'claude', false, 'written', null, null),
('106', '346',
 'Two heads of industry with private armouries, and T''Challa is the one who has never needed the other''s help. Wakandan vibranium underwrites a great deal of Stark''s best work, a debt Stark acknowledges more readily than most.',
 'claude', false, 'written', null, null),
('346', 'cv-3200',
 'Natasha Romanoff was sent to spy on Stark Industries and ended up working as Stark''s assistant, then as his teammate. He has never entirely forgotten how the introduction was arranged.',
 'claude', false, 'written', null, 'ally'),
('346', '620',
 'Stark has been Parker''s patron and his worst influence by turns — the man who built him a better suit and then asked him to sign a registration act. Parker keeps outgrowing the mentorship.',
 'claude', false, 'written', null, null),
('346', '717',
 'Stark funds the future and Logan is a man who has outlived several of them. They served together on the Avengers and disagreed about nearly everything, most sharply about whether killing is ever simply the efficient answer.',
 'claude', false, 'written', null, null),
('226', '332',
 'Both founding Defenders — the non-team Strange assembled precisely because none of its members wanted to be on a team. Strange is one of the few people who can move the Hulk somewhere else without fighting him.',
 'claude', false, 'written', null, null),
('226', '346',
 'Two men who were brilliant, arrogant, and then broken by their own hands — Strange''s in a car crash, Stark''s in his chest. Both rebuilt themselves around the injury, and neither was especially humbled by it.',
 'claude', false, 'written', null, null),
('226', '620',
 'Strange is the adult Parker goes to when the problem is not punchable, which has become one of the character''s most reliable arrangements. Strange finds him tolerable, which from Strange is warmth.',
 'claude', false, 'written', null, null),
('332', '620',
 'Two of Marvel''s accidental radiation casualties, and Parker is among the few who treat the Hulk as someone to talk down rather than something to contain. They have fought; it has never been personal.',
 'claude', false, 'written', null, 'ally'),
('332', 'cv-3200',
 'Romanoff is the Avenger sent to fetch Banner, which the team treats as routine and she does not. The job means walking unarmed toward the one thing on the roster that cannot be reliably talked down.',
 'claude', false, 'written', null, null),
('332', '655',
 'Thanos treats the Hulk as a problem of scale rather than a person, which is the only approach that has ever reliably worked. Being outmatched has never once registered with the Hulk as a reason to stop.',
 'claude', false, 'written', null, null),
('332', 'cv-4324',
 'Loki is the reason the Hulk was hunted in Avengers #1 — the scheme that brought the team together was built on framing him for it. The Hulk quit the roster one issue later.',
 'claude', false, 'written', null, null),
('620', '717',
 'Logan finds Parker exhausting and Parker finds Logan appalling, and they have carried each other off the field more times than either mentions. The friendship lives entirely in what neither will say about it.',
 'claude', false, 'written', null, null),
('213', '620',
 'Deadpool''s red suit and running commentary are a deliberate riff on Spider-Man, and Marvel eventually gave the joke its own book by co-heading them in a 2016 series. Parker refuses to be amused, which is the engine of it.',
 'claude', false, 'written', null, 'ally'),

-- ── DC: Gotham ────────────────────────────────────────────────────────────
('63', '69',
 'Barbara Gordon put on the cowl without being asked and Batman spent years trying to send her home. After the Joker shot her she rebuilt herself as Oracle, and became the person the whole family reports to.',
 'claude', false, 'written', null, null),
('165', '370',
 'Selina Kyle is a thief and the Joker is not, which is the entire distance between them. She has no patience for a man who burns money, and he has never known what to do with someone unimpressed.',
 'claude', false, 'written', null, null),
('165', '309',
 'They founded the Gotham City Sirens together with Poison Ivy — a book premised on three of Batman''s rogues sharing an apartment. Calling them enemies misses that they have been written as each other''s only reliable company.',
 'claude', false, 'written', null, 'ally'),
('309', '370',
 'Harleen Quinzel was his psychiatrist at Arkham and became his accomplice, and the modern character is built entirely around getting out. Her being his enemy is recent, hard-won, and the best thing that ever happened to her.',
 'claude', false, 'written', null, null),
('370', '63',
 'The Joker shot Barbara Gordon through the spine to make a point to her father, and she is the injury the character was never allowed to take back. She rebuilt herself as Oracle; he has never once been made to account for it.',
 'claude', false, 'written', null, null),
('370', '405',
 'Two men who each consider themselves the smartest in the room and cannot stand being in it together. Luthor keeps recruiting him into villain coalitions and keeps rediscovering that the Joker has no interest in winning.',
 'claude', false, 'written', null, 'ally'),
('370', 'cv-6129',
 'Bane emptied Arkham Asylum to exhaust Batman before facing him himself, which put the Joker on the street as an instrument rather than a rival. It is the only time anyone has used him as an opening move.',
 'claude', false, 'written', null, null),
('370', 'cv-4885',
 'Gotham''s two oldest rogues — the Joker arrived in 1940, Cobblepot in 1941 — and the alliance never holds. Cobblepot runs a business, and the Joker is a liability to one.',
 'claude', false, 'written', null, null),
('370', 'cv-3718',
 'Both are built on compulsion: the Riddler cannot help leaving the clue, the Joker cannot help needing the audience. The Riddler resents the comparison, considering himself a professional and the Joker a mess.',
 'claude', false, 'written', null, null),
('405', '69',
 'Luthor''s problem with Batman is that he is not impressed. He is the one adversary who is also a self-made man with money, and who therefore reads the philanthropy for exactly what it is.',
 'claude', false, 'written', null, null),
('17', '370',
 'Alfred has patched up everything the Joker has done to that family for decades, which makes him the one man in Gotham holding a complete account of the cost. He has never been the one arguing for the rule.',
 'claude', false, 'written', null, null),
('17', '644',
 'Superman is among the very few people who get past the Batcave''s door, and Alfred receives him the way he receives everyone — politely, with tea, and without treating a Kryptonian as an occasion.',
 'claude', false, 'written', null, null),
('69', 'cv-1808',
 'Lois Lane could unmask him and has chosen not to, which Batman finds harder to accept than a threat. She is Superman''s evidence that trusting people works, aimed squarely at the man who disagrees.',
 'claude', false, 'written', null, null),
('69', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471',
 'The World''s Greatest Detective and the man who can outrun the answer. Barry Allen is a forensic scientist by trade, which makes him the only Leaguer who does Batman''s actual job.',
 'claude', false, 'written', null, null),

-- ── DC: the League ────────────────────────────────────────────────────────
('38', '69',
 'Founding Justice Leaguers who barely overlap: Batman works one city after dark and Arthur answers to two-thirds of the planet. Batman''s contingency for him involves dehydration, and Arthur has never pretended to be surprised.',
 'claude', false, 'written', null, null),
('38', '644',
 'Two of the League''s heavy hitters and the two most often written as lonely — one the last of a dead world, the other a king his own people keep refusing.',
 'claude', false, 'written', null, null),
('38', '720',
 'Both rule, or are meant to, and both left home to work with surface-dwellers who find their politics inconvenient. Diana is the Leaguer who treats Atlantis as a nation rather than as a location.',
 'claude', false, 'written', null, null),
('405', '720',
 'Luthor has run for president, run the League''s rival roster, and stayed legally untouchable through most of it. Diana is the Leaguer least willing to respect any of those positions.',
 'claude', false, 'written', null, null),
('370', '644',
 'The Joker has almost no business in Metropolis, which is what made Emperor Joker land: handed Mister Mxyzptlk''s power, the first thing he did was remake reality and keep Superman alive to watch it.',
 'claude', false, 'written', null, null),
('643', '69',
 'Kara Zor-El is the Kryptonian Batman keeps a plan for and does not apologise about. She was raised on Krypton and remembers it, which makes her considerably less predictable to him than her cousin.',
 'claude', false, 'written', null, 'ally'),
('644', 'cv-1691',
 'Dick Grayson is the one member of Batman''s family Superman treats as a peer rather than as Batman''s business. Superman has repeatedly named him the best of them, and Bruce has never contradicted it.',
 'claude', false, 'written', null, null),
('720', 'cv-1808',
 'Two women who built careers on refusing to be protected, in a universe that keeps trying anyway. Lois is among the few who report on Diana as a head of state rather than as a spectacle.',
 'claude', false, 'written', null, null),

-- ── Star Wars ─────────────────────────────────────────────────────────────
('208', '418',
 'The reveal that reorganised the whole saga: Vader is Luke Skywalker''s father, and says so mid-duel immediately after taking his hand. Everything afterwards is Luke refusing what that is supposed to mean.',
 'claude', false, 'written', null, null),
('208', 'cv-33545',
 'Vader interrogated Leia Organa, then had her watch her homeworld destroyed, all before either of them knew she was his daughter. The films never give them a scene after the reveal.',
 'claude', false, 'written', null, null),
('208', 'cv-2206',
 'Obi-Wan Kenobi trained Anakin Skywalker, fought him beside a lava flow, and left him burning. When they meet again twenty years later Vader kills him in four moves, and Kenobi lets it happen.',
 'claude', false, 'written', null, null),
('208', 'cv-2608',
 'Vader froze Han Solo in carbonite chiefly to test whether the process was survivable, intending to use it on Luke. Solo is the one person he harms as an experiment rather than as an enemy.',
 'claude', false, 'written', null, null),
('208', 'cv-6335',
 'Anakin Skywalker built C-3PO as a boy on Tatooine. By the time they share a scene as Vader and the droid, neither of them acknowledges it, and only the audience is carrying the information.',
 'claude', false, 'written', null, null),

-- ── Animation ─────────────────────────────────────────────────────────────
('cv-2936', 'h_42f7e0df-0aba-42b6-861f-09bec419704c',
 'Goofy is the friend Mickey Mouse never has to manage — he turns up already agreeable, which in a cast built around Donald''s temper is a job of its own.',
 'claude', false, 'written', null, null),
('cv-2859', 'cv-2860',
 'Porky Pig headlined Looney Tunes before Bugs Bunny existed and was quietly demoted to supporting player once he did. He still closes the cartoons Bugs starred in.',
 'claude', false, 'written', null, null),
('cv-2860', 'cv-2861',
 'Elmer Fudd has hunted Bugs Bunny since 1940 and has never once succeeded, which is the premise rather than a failure of it. The joke only works because Elmer is entirely sincere.',
 'claude', false, 'written', null, null),

-- ── Declines: real pair, nothing specific and true to add ─────────────────
('h_9a0e3d34-dbda-4b55-9944-e7b6bfbcd280', 'h_e3dbea9a-11ee-4415-b75c-4812d2865ab1',
 null, 'claude', false, 'nothing_to_say', 'Disney ensemble cast-mates; no defined relationship between them', null),
('cv-2936', 'h_e3dbea9a-11ee-4415-b75c-4812d2865ab1',
 null, 'claude', false, 'nothing_to_say', 'Disney ensemble cast-mates; no defined relationship between them', null),
('370', '720',
 null, 'claude', false, 'nothing_to_say', 'meet only in League-wide crossovers; no rivalry of their own', null),
('165', '644',
 null, 'claude', false, 'nothing_to_say', 'Gotham/Metropolis crossover adjacency; not an enmity', null),
('165', '720',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', '644',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', '720',
 null, 'claude', false, 'nothing_to_say', 'Suicide Squad/League crossovers; no defined relationship', null),
('370', '38',
 null, 'claude', false, 'nothing_to_say', 'no meaningful shared history', null),
('620', 'cv-3200',
 null, 'claude', false, 'nothing_to_say', 'Avengers-adjacent only; no defined Parker/Romanoff relationship', null),
('106', '332',
 null, 'claude', false, 'nothing_to_say', 'teammates; nothing specific beyond the roster', null),
('106', '620',
 null, 'claude', false, 'nothing_to_say', 'teammates; nothing specific beyond the roster', null),
('149', '527',
 null, 'claude', false, 'nothing_to_say', 'both team leaders; no relationship of their own', null),
('332', '527',
 null, 'claude', false, 'nothing_to_say', 'occasional psychic confrontation; nothing durable', null),
('346', '527',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('370', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471',
 null, 'claude', false, 'nothing_to_say', 'the Flash has his own rogues; no Joker history worth stating', null),
('370', 'cv-1808',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('370', 'cv-1691',
 null, 'claude', false, 'nothing_to_say', 'real but indirect — the Joker''s damage to Dick runs through Jason Todd', null),
('644', 'cv-6129',
 null, 'claude', false, 'nothing_to_say', 'Bane is a Gotham figure; no Superman history', null),
('644', 'cv-3718',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('720', 'cv-1691',
 null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('720', 'cv-3718',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('38', '63',
 null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('38', '405',
 null, 'claude', false, 'nothing_to_say', 'League-wide antagonism; nothing between these two', null),
('165', '38',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('165', '63',
 null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing specific between them', null),
('165', '405',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', '38',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', '63',
 null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('309', '405',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('149', 'h_39f78998-cf7e-411c-a5a9-810f483a3675',
 null, 'claude', false, 'nothing_to_say', 'Infinity-era crossover adjacency; nothing specific', null),
('149', '630',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('149', '638',
 null, 'claude', false, 'nothing_to_say', 'Avengers/X-Men adjacency; nothing specific between them', null),
('149', '687',
 null, 'claude', false, 'nothing_to_say', 'Venom belongs to Spider-Man; no Rogers history', null),
('332', 'h_39f78998-cf7e-411c-a5a9-810f483a3675',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('332', '630',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('332', '638',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('332', '687',
 null, 'claude', false, 'nothing_to_say', 'have fought; nothing durable to state', null),
('346', 'h_39f78998-cf7e-411c-a5a9-810f483a3675',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('346', '423',
 null, 'claude', false, 'nothing_to_say', 'Magneto belongs to the X-Men; no Stark history worth stating', null),
('346', '630',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('213', '346',
 null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('208', 'cv-6334',
 null, 'claude', false, 'nothing_to_say', 'no scene of consequence between them', null),
('208', 'cv-2594',
 null, 'claude', false, 'nothing_to_say', 'no relationship; R2 was Anakin''s but the films never use it', null),
('208', '729',
 null, 'claude', false, 'nothing_to_say', 'never meet — Yoda fights Palpatine, not Vader', null),

-- ── Declines: the edge itself is a ComicVine artifact ─────────────────────
('h_17ba56f7-0061-4121-b280-f01d36580cee', 'h_2363f39d-2303-4f6d-a06e-f56dc0c41d28',
 null, 'claude', false, 'no_relationship', 'linked only by both carrying publisher "In the Public Domain"', null),
('h_2363f39d-2303-4f6d-a06e-f56dc0c41d28', 'h_7906ea98-fdb9-4e3f-9fca-1f905fe003c5',
 null, 'claude', false, 'no_relationship', 'linked only by both carrying publisher "In the Public Domain"', null)
on conflict (hero_a, hero_b) do nothing;
