-- Relationship blurbs, batch 02. Queue pairs 101-200 by combined fame.
-- 38 written, 60 nothing_to_say, 2 no_relationship, 5 kind corrections.
--
-- The decline rate is up sharply from batch 01 (46% -> 62%). This band is where
-- the shared-publisher crossover pairs concentrate: every Spider-Man villain
-- against every Avenger, every Gotham rogue against every Leaguer. Those
-- declines are the design working — describeRelationship()'s templated line
-- already says the true thing about Iron Man and Doctor Octopus.
--
-- Notable kind corrections, all Star Wars: Luke/Leia arrived as 'ally' (they are
-- twins), Luke/Obi-Wan and Luke/Yoda as 'family' (they are mentors),
-- Vader/Palpatine and Boba Fett/Vader as 'enemy' (master and apprentice;
-- employer and bounty hunter). Kinship in that franchise is close to inverted.
--
-- This file was reconstructed from the applied rows via
--   node scripts/apply-relationship-blurbs.mjs --dump <ts> <out.sql>
-- after the batch was applied through the MCP tool without its file being
-- written first. Verified byte-equivalent by re-parsing: 100 rows, 38/60/2.
insert into public.hero_relationship_blurbs
  (hero_a, hero_b, blurb, author, verified, status, note, kind_correction)
values
('h_2363f39d-2303-4f6d-a06e-f56dc0c41d28', 'h_58c98d94-8f76-48a2-9adb-9ee7de1c41aa', null, 'claude', false, 'no_relationship', 'linked only by both carrying publisher "In the Public Domain"', null),
('h_9a0e3d34-dbda-4b55-9944-e7b6bfbcd280', 'h_f6db7814-5492-404e-bfa7-603a3b88fd71', null, 'claude', false, 'no_relationship', 'linked only by both carrying publisher "Disney"; different studios and eras', null),
('106', '313', null, 'claude', false, 'nothing_to_say', 'Avengers adjacency; nothing specific', null),
('106', '527', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('106', '655', null, 'claude', false, 'nothing_to_say', 'Infinity-era adjacency; nothing specific', null),
('106', '717', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('106', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'Avengers adjacency; nothing specific', null),
('149', '225', null, 'claude', false, 'nothing_to_say', 'Doctor Octopus belongs to Spider-Man', null),
('149', '299', null, 'claude', false, 'nothing_to_say', 'Green Goblin belongs to Spider-Man', null),
('149', '566', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('165', '643', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('165', 'cv-1691', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('165', 'cv-1808', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('165', 'cv-3718', null, 'claude', false, 'nothing_to_say', 'both Gotham rogues; no relationship of their own', null),
('165', 'cv-4885', null, 'claude', false, 'nothing_to_say', 'both Gotham rogues; no relationship of their own', null),
('165', 'cv-6129', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('165', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('17', '309', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('17', 'cv-3718', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('17', 'cv-4885', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('17', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471', null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('213', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('225', '346', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('226', '313', null, 'claude', false, 'nothing_to_say', 'Avengers adjacency; nothing specific', null),
('226', '527', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('226', '717', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('226', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'Avengers adjacency; nothing specific', null),
('299', '332', null, 'claude', false, 'nothing_to_say', 'Green Goblin belongs to Spider-Man', null),
('299', '346', null, 'claude', false, 'nothing_to_say', 'Green Goblin belongs to Spider-Man', null),
('30', '620', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', 'cv-1691', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('309', 'cv-1808', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('309', 'cv-3718', null, 'claude', false, 'nothing_to_say', 'both Gotham rogues; no relationship of their own', null),
('309', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('313', '655', null, 'claude', false, 'nothing_to_say', 'Infinity-era adjacency; nothing specific', null),
('332', '566', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('332', '714', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('332', 'cv-3202', null, 'claude', false, 'nothing_to_say', 'Fury has hunted the Hulk; nothing durable to state', null),
('346', '566', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('346', '638', null, 'claude', false, 'nothing_to_say', 'Avengers/X-Men adjacency', null),
('346', '687', null, 'claude', false, 'nothing_to_say', 'Venom belongs to Spider-Man; no Stark history', null),
('346', '714', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('38', '643', null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('38', 'cv-1691', null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('38', 'cv-1808', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('38', 'cv-4885', null, 'claude', false, 'nothing_to_say', 'Penguin is a Gotham figure; no Aquaman history', null),
('38', 'h_2ace1789-18f4-43bb-8f5f-030acaed0471', null, 'claude', false, 'nothing_to_say', 'League adjacency; nothing specific', null),
('405', '63', null, 'claude', false, 'nothing_to_say', 'Metropolis/Gotham crossover adjacency', null),
('405', 'cv-1691', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('405', 'cv-6129', null, 'claude', false, 'nothing_to_say', 'occasional coalition; nothing durable', null),
('423', '620', null, 'claude', false, 'nothing_to_say', 'crossover adjacency; not allies in any sense', null),
('566', '620', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('620', '630', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('620', 'cv-4324', null, 'claude', false, 'nothing_to_say', 'Loki belongs to Thor; no durable Spider-Man history', null),
('620', 'h_39f78998-cf7e-411c-a5a9-810f483a3675', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('655', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('717', 'cv-3200', null, 'claude', false, 'nothing_to_say', 'both Avengers-adjacent; nothing specific between them', null),
('cv-1691', 'cv-4885', null, 'claude', false, 'nothing_to_say', 'Gotham adjacency; nothing durable', null),
('cv-1808', 'cv-3718', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('cv-2936', 'h_568d2a22-ba40-453a-a725-ddca7b60309a', null, 'claude', false, 'nothing_to_say', 'meet only via Kingdom Hearts; too tenuous to state', null),
('cv-3200', 'h_39f78998-cf7e-411c-a5a9-810f483a3675', null, 'claude', false, 'nothing_to_say', 'crossover adjacency only', null),
('h_568d2a22-ba40-453a-a725-ddca7b60309a', 'h_9a0e3d34-dbda-4b55-9944-e7b6bfbcd280', null, 'claude', false, 'nothing_to_say', 'meet only via Kingdom Hearts; too tenuous to state as a relationship', null),
('106', '226', 'The king of Wakanda and the Sorcerer Supreme are Marvel''s two great gatekeepers — one guards a border, the other a dimension. Both are used to being the most informed person present and neither enjoys the other.', 'claude', false, 'written', null, null),
('127', '208', 'Boba Fett works for Vader on Bespin and is the only bounty hunter Vader bothers to warn about damaging the merchandise. It is as close to professional respect as either of them offers anyone.', 'claude', false, 'written', null, 'ally'),
('149', '30', 'Hank Pym was there at the Avengers'' founding and Rogers arrived three issues later to lead them, which Pym has never entirely made peace with. He built the team; the man out of the ice got it.', 'claude', false, 'written', null, null),
('149', '714', 'Bucky Barnes was Rogers'' closest friend, fell from a train in 1945, and came back as a Soviet weapon who did not know him. Rogers has never once accepted that the Winter Soldier is a different person.', 'claude', false, 'written', null, null),
('149', 'cv-2151', 'Reed Richards is the smartest man in the room and Rogers is the one he defers to anyway. Their Civil War split cost more than most because Richards had run the numbers and Rogers simply refused them.', 'claude', false, 'written', null, null),
('149', 'cv-3202', 'Nick Fury commanded the unit Rogers fought beside in the war and ran the agency that thawed him out. He is the only person who has known Rogers in both centuries.', 'claude', false, 'written', null, null),
('165', '17', 'Alfred is the only member of the household who has treated Selina Kyle as a guest rather than a case, which she has never quite known what to do with. He has served her tea in the Batcave.', 'claude', false, 'written', null, null),
('17', '63', 'Alfred treats Barbara Gordon as the one member of the operation who arrived by choice rather than by grief. He is also the only person in the Batcave who has never once suggested she stop.', 'claude', false, 'written', null, null),
('17', 'cv-1691', 'Alfred raised Dick Grayson as much as Bruce Wayne did, and was the one arguing for the boy to have a childhood. When Dick left to become Nightwing, Alfred was the only one who called it growth.', 'claude', false, 'written', null, null),
('17', 'cv-6129', 'Bane broke Bruce Wayne''s back and Alfred is the man who nursed him through the year it took to come back. He had warned him, and said so exactly once.', 'claude', false, 'written', null, null),
('208', 'cv-16164', 'Palpatine spent decades grooming Anakin Skywalker and got Vader, an apprentice he kept deliberately crippled so he could never win the succession. Vader kills him the moment his son is on the floor.', 'claude', false, 'written', null, 'ally'),
('213', '717', 'Wade Wilson''s healing factor is a botched attempt to copy Logan''s, which makes Deadpool a failed forgery of a man he cannot stop bothering. Logan''s response has been consistent for thirty years.', 'claude', false, 'written', null, null),
('226', '655', 'Strange is the one who does the arithmetic on Thanos — the character whose whole function is knowing exactly how bad the odds are and proceeding anyway. He is also the one who folds first, deliberately.', 'claude', false, 'written', null, null),
('289', 'cv-40722', 'Vegeta arrived to kill Goku and stayed for forty years of coming second. He is the prince of a dead race losing repeatedly to a low-class warrior who has never once noticed it was a competition.', 'claude', false, 'written', null, null),
('30', '332', 'Hank Pym and Bruce Banner are both scientists undone by their own experiment, and both founded the Avengers. Pym is the one the team keeps forgiving; Banner is the one it keeps preparing for.', 'claude', false, 'written', null, null),
('30', '346', 'Two of the Avengers'' founding engineers, and the comparison has never been kind to Pym: Stark''s worst inventions are weapons, and Pym''s worst invention was Ultron.', 'claude', false, 'written', null, null),
('309', 'cv-6129', 'Squadmates on the Suicide Squad, which pairs Gotham''s least compatible criminals under a bomb collar. Bane is a strategist and Harley Quinn is a hazard, and the arrangement holds only as long as the mission does.', 'claude', false, 'written', null, null),
('313', 'cv-3200', 'Clint Barton was sent to kill Natasha Romanoff and recruited her instead, which is the single decision the modern Avengers rest on. Neither has ever described it as anything other than a job call.', 'claude', false, 'written', null, null),
('346', 'cv-2151', 'Stark and Richards ran the Illuminati together — a secret committee of Marvel''s smartest men deciding things on everyone else''s behalf. Nearly every catastrophe they were formed to prevent, they caused.', 'claude', false, 'written', null, null),
('346', 'cv-3202', 'Fury is the man who knows what Stark''s weapons were used for before Stark stopped making them, and has never needed to say so aloud. The leverage is permanent and neither pretends otherwise.', 'claude', false, 'written', null, null),
('405', 'cv-1808', 'Lois Lane has been investigating Lex Luthor for as long as she has been reporting, and he has never once been able to buy, sue or intimidate the paper into dropping it. He respects her considerably more than he respects Superman.', 'claude', false, 'written', null, null),
('418', '729', 'Yoda trained Luke Skywalker in a swamp while insisting he was too old, too angry and too impatient, and was right about all three. Luke left before finishing and it cost him a hand.', 'claude', false, 'written', null, 'ally'),
('418', 'cv-2206', 'Obi-Wan Kenobi watched over Luke Skywalker from a distance for nineteen years, trained him for days, and died in front of him to buy an escape. Almost everything he told Luke about his father was a lie.', 'claude', false, 'written', null, 'ally'),
('418', 'cv-2594', 'R2-D2 carried the message that started Luke Skywalker''s war and then flew in his X-wing for every battle after. The astromech is the one companion who has been present for the entire arc.', 'claude', false, 'written', null, null),
('418', 'cv-2608', 'Luke Skywalker went to Mos Eisley looking for a pilot and found a smuggler who came back for him. Solo returning at Yavin is the moment the film decides he is not the cynic he has been playing.', 'claude', false, 'written', null, null),
('418', 'cv-33545', 'Luke Skywalker and Leia Organa are twins, separated at birth and hidden from their father — which the films reveal only after she has kissed him. Neither had any idea until Yoda said so.', 'claude', false, 'written', null, 'family'),
('418', 'cv-6334', 'Chewbacca flew with Luke Skywalker for three films and is the one member of the crew who never had a falling-out with him. They share almost no dialogue, which is the point of a Wookiee.', 'claude', false, 'written', null, null),
('418', 'cv-6335', 'C-3PO was built by Luke Skywalker''s father and ends up serving the son, a fact the protocol droid is never told. He is Luke''s inheritance and treats himself as a household appliance.', 'claude', false, 'written', null, null),
('423', '717', 'Magneto controls metal and Logan''s skeleton is laced with it, which makes their every fight embarrassingly one-sided until Logan gets close. Magneto has torn the adamantium out through his pores at least once.', 'claude', false, 'written', null, null),
('63', 'cv-6129', 'Bane broke Batman''s back and Barbara Gordon was shot through hers, and they are the two people in Gotham who understand what the year afterwards actually costs. It has never once made them sympathetic to each other.', 'claude', false, 'written', null, null),
('cv-1691', 'cv-1808', 'Lois Lane and Dick Grayson are the two people who know both secrets and neither identity is theirs to keep. She has covered him as a reporter more than once and never once written the part she knows.', 'claude', false, 'written', null, null),
('cv-1691', 'cv-6129', 'Bane is the man who broke the person Dick Grayson was raised by, and Nightwing is the one who had to put on the cowl afterwards. He has never fought Bane on his own terms — only in his father''s.', 'claude', false, 'written', null, null),
('cv-2608', 'cv-33545', 'Leia Organa spends two films telling Han Solo exactly what she thinks of him and one telling him she loves him, in that order. He is frozen in carbonite before he can answer.', 'claude', false, 'written', null, null),
('cv-2608', 'cv-6334', 'Han Solo and Chewbacca have flown together since before the films start, and the Wookiee life debt is the only obligation Solo has never tried to talk his way out of. Neither needs the other translated.', 'claude', false, 'written', null, null),
('cv-2608', 'cv-6335', 'C-3PO computes the odds and Han Solo has never once wanted to hear them, which is the running joke of the whole trilogy. The droid is right every time and it changes nothing.', 'claude', false, 'written', null, null),
('cv-2860', 'cv-3162', 'Yosemite Sam is the rootinest tootinest hunter in the west and has never landed a shot on Bugs Bunny. Where Elmer Fudd is defeated by his own decency, Sam is defeated entirely by his temper.', 'claude', false, 'written', null, null),
('cv-6334', 'cv-6335', 'A Wookiee who cannot be understood and a protocol droid fluent in six million forms of communication, permanently stuck with each other. Chewbacca reassembles him after Cloud City and does not enjoy it.', 'claude', false, 'written', null, null),
('h_2704ac68-9389-46e8-ad4e-b847d94d53d4', 'h_fe4d8b42-81a9-4438-89a0-a7b51ed195ec', 'Hera and Aphrodite are both Olympians and rivals in the myth that starts the Trojan War: Paris was asked to name the fairest, and Aphrodite bought the verdict with Helen. Hera spent the whole war on the other side.', 'claude', false, 'written', null, null)
on conflict (hero_a, hero_b) do nothing;
